---
- name: Converge - Test services deployment
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Determine infrastructure project root
      ansible.builtin.set_fact:
        infrastructure_root: "/opt/infrastructure"

    - name: Show infrastructure project root
      ansible.builtin.debug:
        var: infrastructure_root

    - name: Create inventory for services test
      ansible.builtin.copy:
        dest: /tmp/services_inventory.yml
        content: |
          all:
            children:
              homelab:
                hosts:
                  localhost:
                    ansible_connection: local
                    ansible_host: localhost
                    ansible_python_interpreter: "{{ ansible_python.executable }}"
        mode: '0644'

    - name: Run staged bootstrap deploy playbook (prerequisite)
      ansible.builtin.shell: |
        cd /tmp
        ansible-playbook -i services_inventory.yml \
          -e docker_skip_compose=true \
          "{{ infrastructure_root }}/playbooks/docker-deploy-bootstrap.yml"
      args:
        executable: /bin/bash
      environment:
        ANSIBLE_HOST_KEY_CHECKING: "False"
      register: services_bootstrap
      changed_when: false
      failed_when: services_bootstrap.rc != 0

    - name: Run staged services deploy playbook
      ansible.builtin.shell: |
        cd /tmp
        ansible-playbook -i services_inventory.yml \
          -e docker_skip_compose=true \
          "{{ infrastructure_root }}/playbooks/docker-deploy-services.yml"
      args:
        executable: /bin/bash
      environment:
        ANSIBLE_HOST_KEY_CHECKING: "False"
      register: services_deploy
      changed_when: false
      failed_when: services_deploy.rc != 0

    - name: Run services health check playbook
      ansible.builtin.shell: |
        cd /tmp
        ansible-playbook -i services_inventory.yml \
          -e skip_oauth_health=true \
          "{{ infrastructure_root }}/playbooks/docker-check-health.yml"
      args:
        executable: /bin/bash
      environment:
        ANSIBLE_HOST_KEY_CHECKING: "False"
        DOMAIN: "test.local"
        ZITADEL_PUBLIC_DOMAIN: "auth.test.local"
      register: services_health
      changed_when: false
      failed_when: services_health.rc != 0

    - name: Display services health result
      ansible.builtin.debug:
        var: services_health
