---
- name: Converge - Test services deployment
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Determine infrastructure project root
      ansible.builtin.set_fact:
        infrastructure_root: >-
          {{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY')
             | default(playbook_dir | dirname | dirname, true) }}
      delegate_to: localhost
      become: false
      run_once: true

    - name: Show infrastructure project root
      ansible.builtin.debug:
        var: infrastructure_root

    - name: Create inventory for services test
      ansible.builtin.copy:
        dest: /tmp/services_inventory.yml
        content: |
          all:
            children:
              homelab:
                hosts:
                  molecule-infra:
                    ansible_host: localhost
                    ansible_port: 32222
                    ansible_user: rzp-admin
                    ansible_ssh_private_key_file: "{{ lookup('env', 'ORBSTACK_SSH_KEY') | default('~/.orbstack/ssh/id_ed25519', true) }}"
                    ansible_python_interpreter: /usr/bin/python3
        mode: '0644'
      delegate_to: localhost
      become: false
      run_once: true

    - name: Run foundation bootstrap (socket proxy only) for test host
      ansible.builtin.shell: |
        cd "{{ infrastructure_root }}"
        ansible-playbook -i /tmp/services_inventory.yml \
          playbooks/docker-bootstrap-foundation.yml
      args:
        executable: /bin/bash
      environment:
        ANSIBLE_HOST_KEY_CHECKING: "False"
        ANSIBLE_CONFIG: "{{ infrastructure_root }}/ansible.cfg"
        ANSIBLE_REMOTE_TMP: "/tmp/.ansible-tmp"
      register: foundation_bootstrap
      changed_when: false
      failed_when: foundation_bootstrap.rc != 0
      delegate_to: localhost
      become: false
      run_once: true

    - name: Run staged services deploy playbook
      ansible.builtin.shell: |
        cd "{{ infrastructure_root }}"
        ansible-playbook -i /tmp/services_inventory.yml \
          -e services_allow_fake_dri=true \
          playbooks/docker-deploy-services.yml
      args:
        executable: /bin/bash
      environment:
        ANSIBLE_HOST_KEY_CHECKING: "False"
        ANSIBLE_CONFIG: "{{ infrastructure_root }}/ansible.cfg"
        ANSIBLE_REMOTE_TMP: "/tmp/.ansible-tmp"
      register: services_deploy
      changed_when: false
      failed_when: services_deploy.rc != 0
      delegate_to: localhost
      become: false
      run_once: true

    - name: Run services health check playbook
      ansible.builtin.shell: |
        cd "{{ infrastructure_root }}"
        ansible-playbook -i /tmp/services_inventory.yml \
          -e skip_oauth_health=true \
          playbooks/docker-check-health.yml
      args:
        executable: /bin/bash
      environment:
        ANSIBLE_HOST_KEY_CHECKING: "False"
        DOMAIN: "test.local"
        ANSIBLE_CONFIG: "{{ infrastructure_root }}/ansible.cfg"
        ANSIBLE_REMOTE_TMP: "/tmp/.ansible-tmp"
      register: services_health
      changed_when: false
      failed_when: services_health.rc != 0
      delegate_to: localhost
      become: false
      run_once: true

    - name: Display services health result
      ansible.builtin.debug:
        var: services_health
