---
# Molecule scenario for testing services deployment flow
# Tests staged services deployment on top of bootstrap

dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml

driver:
  name: docker

platforms:
  - name: instance
    image: geerlingguy/docker-debian13-ansible:latest
    pre_build_image: true
    privileged: true
    capabilities:
      - ALL
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/run/docker.sock:/var/run/docker.sock
    cgroupns_mode: host
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /tmp
    networks:
      - name: molecule-test-network

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callbacks_enabled: timer
      stdout_callback: ansible.builtin.default
    ssh_connection:
      pipelining: true
  inventory:
    host_vars:
      instance:
        ansible_user: root
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
    verify: verify.yml
  lint: |
    set -e
    yamllint .
    ansible-lint

verifier:
  name: ansible

scenario:
  name: services
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
