---
# Molecule scenario for testing services deployment flow
# Tests staged services deployment on top of bootstrap

dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml

driver:
  name: default
  options:
    managed: false

platforms:
  - name: molecule-infra
    address: localhost
    user: default
    port: 32222
    identity_file: "{{ lookup('env', 'ORBSTACK_SSH_KEY') | default('~/.orbstack/ssh/id_ed25519', true) }}"
    groups:
      - services_targets

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callbacks_enabled: timer
      stdout_callback: ansible.builtin.default
    ssh_connection:
      pipelining: true
  inventory:
    host_vars:
      molecule-infra:
        ansible_host: localhost
        ansible_port: 32222
        ansible_user: default
        ansible_ssh_private_key_file: "{{ lookup('env', 'ORBSTACK_SSH_KEY') | default('~/.orbstack/ssh/id_ed25519', true) }}"
        ansible_python_interpreter: /usr/bin/python3
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
    verify: verify.yml
  lint: |
    set -e
    yamllint .
    ansible-lint

verifier:
  name: ansible

scenario:
  name: services
  test_sequence:
    - dependency
    - syntax
    - prepare
    - converge
    - idempotence
    - verify
