---
- name: Prepare for services test
  hosts: all
  become: true
  gather_facts: true

  vars:
    docker_compose_version: "v2.24.6"
    docker_compose_arch_map:
      aarch64: linux-aarch64
      arm64: linux-aarch64
      x86_64: linux-x86_64
    docker_compose_arch: "{{ docker_compose_arch_map.get(ansible_architecture, 'linux-x86_64') }}"
    docker_compose_url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ docker_compose_arch }}"

  tasks:
    - name: Determine infrastructure project root
      ansible.builtin.set_fact:
        infrastructure_root: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"

    - name: Create inventory for services test (Docker install)
      ansible.builtin.copy:
        dest: /tmp/services_inventory.yml
        content: |
          all:
            children:
              homelab:
                hosts:
                  molecule-infra:
                    ansible_host: localhost
                    ansible_port: 32222
                    ansible_user: rzp-admin
                    ansible_ssh_private_key_file: "{{ lookup('env', 'ORBSTACK_SSH_KEY') | default('~/.orbstack/ssh/id_ed25519', true) }}"
                    ansible_python_interpreter: /usr/bin/python3
        mode: '0644'
      delegate_to: localhost
      become: false
      run_once: true

    - name: Provision Docker and Compose via docker-install playbook
      ansible.builtin.shell: |
        cd "{{ infrastructure_root }}"
        ansible-playbook -i /tmp/services_inventory.yml \
          playbooks/docker-install.yml
      args:
        executable: /bin/bash
      environment:
        ANSIBLE_HOST_KEY_CHECKING: "False"
        ANSIBLE_CONFIG: "{{ infrastructure_root }}/ansible.cfg"
        ANSIBLE_REMOTE_TMP: "/tmp/.ansible-tmp"
      register: docker_install_result
      changed_when: false
      failed_when: docker_install_result.rc != 0
      delegate_to: localhost
      become: false
      run_once: true

    - name: Install base packages required for Molecule host
      ansible.builtin.apt:
        name:
          - ansible
          - docker.io
          - python3-pip
          - rsync
          - git
          - curl
        state: present
        update_cache: true

    - name: Ensure Docker service is enabled and running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Install linting tools for verification
      ansible.builtin.pip:
        name:
          - yamllint
          - ansible-lint
          - docker
          - requests
        state: present
        break_system_packages: true

    - name: Install rsync for services tests
      ansible.builtin.apt:
        name: rsync
        state: present
        update_cache: true

    - name: Ensure stacks directory exists for tests
      ansible.builtin.file:
        path: /tmp/stacks
        state: directory
        mode: "0755"

    - name: Ensure infrastructure playbook directory exists
      ansible.builtin.file:
        path: /opt/infrastructure/playbooks
        state: directory
        mode: "0755"

    - name: Sync playbooks for services tests
      ansible.builtin.copy:
        src: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/playbooks/"
        dest: /opt/infrastructure/playbooks/
        owner: root
        group: root
        mode: "0644"
        directory_mode: "0755"

    - name: Ensure infrastructure stacks directory exists
      ansible.builtin.file:
        path: /opt/infrastructure/stacks
        state: directory
        mode: "0755"

    - name: Sync stacks for services tests
      ansible.builtin.copy:
        src: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/stacks/"
        dest: /opt/infrastructure/stacks/
        owner: root
        group: root
        mode: "0644"
        directory_mode: "0755"

    - name: Copy Makefile for services tests
      ansible.builtin.copy:
        src: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/Makefile"
        dest: /opt/infrastructure/Makefile
        owner: root
        group: root
        mode: "0644"

    - name: Copy ansible.cfg for services tests
      ansible.builtin.copy:
        src: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/ansible.cfg"
        dest: /opt/infrastructure/ansible.cfg
        owner: root
        group: root
        mode: "0644"

    - name: Adjust remote ansible.cfg collections path for Orbstack VM
      ansible.builtin.lineinfile:
        path: /opt/infrastructure/ansible.cfg
        regexp: '^collections_paths\s*='
        line: 'collections_paths       = ~/.ansible/collections:/usr/share/ansible/collections'

    - name: Copy Ansible requirements file
      ansible.builtin.copy:
        src: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/requirements.yml"
        dest: /opt/infrastructure/requirements.yml
        owner: root
        group: root
        mode: "0644"

    - name: Install Ansible collections required by infrastructure
      ansible.builtin.command: >-
        ansible-galaxy collection install -r /opt/infrastructure/requirements.yml --force
      args:
        creates: /root/.ansible/collections/ansible_collections/community/docker
      changed_when: true

    - name: Set environment variables for test
      ansible.builtin.lineinfile:
        path: /etc/environment
        line: "{{ item }}"
        state: present
      loop:
        - "DOMAIN=test.local"
        - "CLOUDFLARE_DNS_API_TOKEN=test-token"
        - "ACME_EMAIL=test@test.local"
        - "TZ=UTC"
        - "DOCKER_USER=1000:1000"

    - name: Ensure rzp-admin user exists for Ansible parity
      ansible.builtin.user:
        name: rzp-admin
        shell: /bin/bash
        groups: sudo
        append: true
        create_home: true
        state: present

    - name: Allow rzp-admin passwordless sudo
      ansible.builtin.copy:
        dest: /etc/sudoers.d/99-rzp-admin
        content: "rzp-admin ALL=(ALL) NOPASSWD:ALL\n"
        owner: root
        group: root
        mode: "0440"

    - name: Ensure rzp-admin SSH directory exists
      ansible.builtin.file:
        path: /home/rzp-admin/.ssh
        state: directory
        owner: rzp-admin
        group: rzp-admin
        mode: "0700"

    - name: Load Orbstack public key for rzp-admin access
      ansible.builtin.set_fact:
        admin_authorized_key: "{{ lookup('file', (lookup('env', 'ORBSTACK_SSH_KEY') | default('~/.orbstack/ssh/id_ed25519', true)) + '.pub') }}"
      delegate_to: localhost
      run_once: true

    - name: Install rzp-admin authorized_keys
      ansible.builtin.copy:
        content: "{{ admin_authorized_key | default('') }}"
        dest: /home/rzp-admin/.ssh/authorized_keys
        owner: rzp-admin
        group: rzp-admin
        mode: "0600"
      when: admin_authorized_key is defined and admin_authorized_key | length > 0

    - name: Ensure traefik network exists
      community.docker.docker_network:
        name: traefik
        state: present
