---
- name: Prepare for services test
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Ensure /usr/local/bin exists
      ansible.builtin.file:
        path: /usr/local/bin
        state: directory
        mode: "0755"

    - name: Install stub docker CLI for Molecule testing
      ansible.builtin.copy:
        dest: /usr/local/bin/docker
        mode: "0755"
        content: |
          #!/bin/bash
          subcommand="$1"
          shift || true

          # Normalize calls like: docker --host unix:///var/run/docker.sock version --format '<json template>'
          if [ "$subcommand" = "--host" ]; then
            shift || true  # skip host value
            subcommand="$1"
            shift || true
          fi

          case "$subcommand" in
            ps)
              cat <<'JSON'
          [{"Names":"docker-socket-proxy","name":"docker-socket-proxy","State":"running","Status":"running","Health":"healthy"}]
          JSON
              ;;
            inspect)
              # Simulate docker inspect returning a running container
              echo "true"
              ;;
            network)
              cat <<'JSON'
          [{"Name":"stacks_socket-proxy"},{"Name":"stacks_traefik"},{"Name":"stacks_zitadel"}]
          JSON
              ;;
            version|info)
              # Always return minimal JSON so docker modules can parse version/info output
              echo '{"Server":{"Version":"24.0.7"},"Client":{"Version":"24.0.7"}}'
              ;;
            compose)
              if [ "$1" = "version" ]; then
                echo "Docker Compose version v2.27.0"
              fi
              ;;
            logs)
              exit 0
              ;;
            *)
              exit 0
              ;;
          esac

    - name: Ensure stub docker CLI is preferred in PATH
      ansible.builtin.lineinfile:
        path: /etc/profile.d/molecule-path.sh
        line: 'export PATH="/usr/local/bin:$PATH"'
        create: true
        mode: "0644"

    - name: Install linting tools for verification
      ansible.builtin.pip:
        name:
          - yamllint
          - ansible-lint
          - docker
          - requests
        state: present
        break_system_packages: true

    - name: Install rsync for services tests
      ansible.builtin.apt:
        name: rsync
        state: present
        update_cache: true

    - name: Ensure stacks directory exists for tests
      ansible.builtin.file:
        path: /tmp/stacks
        state: directory
        mode: "0755"

    - name: Ensure infrastructure playbook directory exists
      ansible.builtin.file:
        path: /opt/infrastructure/playbooks
        state: directory
        mode: "0755"

    - name: Sync playbooks for services tests
      ansible.builtin.copy:
        src: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/playbooks/"
        dest: /opt/infrastructure/playbooks/
        owner: root
        group: root
        mode: "0644"
        directory_mode: "0755"

    - name: Ensure infrastructure stacks directory exists
      ansible.builtin.file:
        path: /opt/infrastructure/stacks
        state: directory
        mode: "0755"

    - name: Sync stacks for services tests
      ansible.builtin.copy:
        src: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/stacks/"
        dest: /opt/infrastructure/stacks/
        owner: root
        group: root
        mode: "0644"
        directory_mode: "0755"

    - name: Copy Makefile for services tests
      ansible.builtin.copy:
        src: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/Makefile"
        dest: /opt/infrastructure/Makefile
        owner: root
        group: root
        mode: "0644"

    - name: Create mock environment variables
      ansible.builtin.set_fact:
        test_domain: "test.local"
        test_zitadel_domain: "auth.test.local"

    - name: Set environment variables for test
      ansible.builtin.lineinfile:
        path: /etc/environment
        line: "{{ item }}"
        state: present
      loop:
        - "DOMAIN=test.local"
        - "ZITADEL_PUBLIC_DOMAIN=auth.test.local"
        - "CLOUDFLARE_DNS_API_TOKEN=test-token"
        - "ACME_EMAIL=test@test.local"
        - "TZ=UTC"
