---
- name: Converge - Test Zitadel OIDC client automation
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Determine infrastructure project root
      ansible.builtin.set_fact:
        infrastructure_root: "/opt/infrastructure"

    - name: Show infrastructure project root
      ansible.builtin.debug:
        var: infrastructure_root

    - name: Create inventory for OIDC client test
      ansible.builtin.copy:
        dest: /tmp/oidc_inventory.yml
        content: |
          all:
            children:
              homelab:
                hosts:
                  localhost:
                    ansible_connection: local
                    ansible_host: localhost
                    ansible_python_interpreter: "{{ ansible_python.executable }}"
        mode: "0644"

    - name: Run staged bootstrap deploy playbook (infrastructure only)
      ansible.builtin.shell: |
        cd /tmp
        ansible-playbook -i oidc_inventory.yml \
          -e docker_skip_compose=true \
          -e enable_zitadel_login_wait=false \
          "{{ infrastructure_root }}/playbooks/docker-deploy-bootstrap.yml"
      args:
        executable: /bin/bash
      environment:
        ANSIBLE_HOST_KEY_CHECKING: "False"
        DOMAIN: "test.local"
        ZITADEL_PUBLIC_DOMAIN: "auth.test.local"
        ZITADEL_PROJECT_NAME: "Default Project"
      register: oidc_bootstrap
      changed_when: false
      failed_when: oidc_bootstrap.rc != 0

    - name: Run Zitadel app configuration playbook
      ansible.builtin.shell: |
        cd /tmp
        ansible-playbook -i oidc_inventory.yml \
          -e docker_skip_compose=true \
          -e zitadel_setup_api_base=http://127.0.0.1:9000/management/v1 \
          "{{ infrastructure_root }}/playbooks/zitadel-configure-apps.yml"
      args:
        executable: /bin/bash
      environment:
        ANSIBLE_HOST_KEY_CHECKING: "False"
        DOMAIN: "test.local"
        ZITADEL_PUBLIC_DOMAIN: "auth.test.local"
        ZITADEL_PROJECT_NAME: "Default Project"
      register: oidc_configure
      changed_when: false
      failed_when: oidc_configure.rc != 0

    - name: Run staged services deploy playbook (cookie secret setup)
      ansible.builtin.shell: |
        cd /tmp
        ansible-playbook -i oidc_inventory.yml \
          -e docker_skip_compose=true \
          "{{ infrastructure_root }}/playbooks/docker-deploy-services.yml"
      args:
        executable: /bin/bash
      environment:
        ANSIBLE_HOST_KEY_CHECKING: "False"
        DOMAIN: "test.local"
        ZITADEL_PUBLIC_DOMAIN: "auth.test.local"
        ZITADEL_PROJECT_NAME: "Default Project"
      register: oidc_services
      changed_when: false
      failed_when: oidc_services.rc != 0

    - name: Display OIDC converge results
      ansible.builtin.debug:
        msg: |
          Bootstrap result rc={{ oidc_bootstrap.rc }}
          Configure result rc={{ oidc_configure.rc }}
          Services result rc={{ oidc_services.rc }}
