---
# Molecule scenario for testing Infrastructure playbooks
# Uses Docker driver with Debian 13 (Trixie) baseline

dependency:
  name: galaxy
  options:
    requirements-file: ../../requirements.yml

driver:
  name: docker

platforms:
  - name: instance
    image: debian:13-slim
    pre_build_image: true
    privileged: false
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /tmp
    networks:
      - name: molecule-test-network

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callbacks_enabled: profile_tasks, timer
      stdout_callback: yaml
    ssh_connection:
      pipelining: true
  inventory:
    host_vars:
      instance:
        ansible_user: root
  playbooks:
    converge: converge.yml
    verify: verify.yml
  lint: |
    set -e
    yamllint .
    ansible-lint

verifier:
  name: ansible

scenario:
  name: default
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
