---
# Molecule verify playbook
# Validates that the infrastructure was deployed correctly

- name: Verify
  hosts: all
  gather_facts: true  # Need facts for ansible_default_ipv4
  become: true

  tasks:
    - name: Verify test directory exists
      ansible.builtin.stat:
        path: /opt/test
      register: test_dir
      failed_when: not test_dir.stat.exists or not test_dir.stat.isdir

    - name: Verify test file exists
      ansible.builtin.stat:
        path: /opt/test/deployment.txt
      register: test_file
      failed_when: not test_file.stat.exists

    - name: Verify test file content
      ansible.builtin.command:
        cmd: cat /opt/test/deployment.txt
      register: file_content
      changed_when: false
      failed_when: "'Test infrastructure' not in file_content.stdout"

    - name: Verify Python is installed
      ansible.builtin.command:
        cmd: python3 --version
      register: python_version
      changed_when: false
      failed_when: python_version.rc != 0

    - name: Display verification results
      ansible.builtin.debug:
        msg:
          - "✓ Test directory exists"
          - "✓ Test file exists with correct content"
          - "✓ Python is installed: {{ python_version.stdout }}"

    # === SECURITY TEST DOCUMENTATION ===
    # Molecule validates syntax only. Production deployments should still perform
    # runtime security checks after Ansible completes:
    #
    # 1. Router ingress closed
    #    - Confirm WAN-facing firewall blocks ports 80/443 entirely
    #    - Example: run external nmap; expect ports filtered/closed
    #
    # 2. Traefik network isolation
    #    - Inspect the `traefik` network and ensure only intended services join it
    #    - Example: docker network inspect traefik --format '{{ '{{' }}len .Containers{{ '}}' }}'
    #
    # 3. Cloudflare token scope
    #    - Verify the DNS API token grants Zone:DNS:Edit for the single zone only
    #    - Example: review token permissions in Cloudflare dashboard/audit logs
    #
    # These checks belong in operational runbooks since Molecule cannot emulate
    # real network boundaries inside the containerized test environment.

    - name: Display security test requirements
      ansible.builtin.debug:
        msg:
          - "Security checklist documented in verify.yml for post-deployment validation"
          - "Follow the comment block above for firewall, network, and DNS token audits"
